name: "Lambda Pull Request"
on:
  pull_request:
    paths:
      - "*-lambda/*"
      - ".github/workflows/**"
  workflow_dispatch: {}

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Package Waitlist Lambda Function
      run: |
        npm ci
        zip -r ../../waitlist-lambda.zip .
      working-directory: lambdas/waitlist

    - name: Package Retry Lambda Function
      run: |
        npm ci
        zip -r ../../retry-lambda.zip .
      working-directory: lambdas/retry

    - name: Package Invoice Lambda Function
      run: |
        npm ci
        zip -r ../../invoice-lambda.zip .
      working-directory: lambdas/invoice

    - name: Package Card Lambda Function
      run: |
        npm ci
        zip -r ../../card-lambda.zip .
      working-directory: lambdas/card-handler
