name: "Lambda Pull Request"
on:
  pull_request:
    paths:
      - "lambdas/**"
      - ".github/workflows/**"
  workflow_dispatch: {}

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # Waitlist Lambda
    - name: Cache NPM for Waitlist Lambda
      uses: actions/cache@v3
      with:
        path: lambdas/waitlist/node_modules
        key: waitlist-${{ runner.os }}-${{ hashFiles('lambdas/waitlist/package-lock.json') }}

    - name: Package Waitlist Lambda Function
      run: |
        npm config set registry https://registry.npmmirror.com
        npm ci
        zip -r ../../waitlist-lambda.zip .
      working-directory: lambdas/waitlist

    # Retry Lambda
    - name: Cache NPM for Retry Lambda
      uses: actions/cache@v3
      with:
        path: lambdas/retry/node_modules
        key: retry-${{ runner.os }}-${{ hashFiles('lambdas/retry/package-lock.json') }}

    - name: Package Retry Lambda Function
      run: |
        npm config set registry https://registry.npmmirror.com
        npm ci
        zip -r ../../retry-lambda.zip .
      working-directory: lambdas/retry

    # Invoice Lambda
    - name: Cache NPM for Invoice Lambda
      uses: actions/cache@v3
      with:
        path: lambdas/invoice/node_modules
        key: invoice-${{ runner.os }}-${{ hashFiles('lambdas/invoice/package-lock.json') }}

    - name: Package Invoice Lambda Function
      run: |
        npm config set registry https://registry.npmmirror.com
        npm ci
        zip -r ../../invoice-lambda.zip .
      working-directory: lambdas/invoice

    # Card Lambda
    - name: Cache NPM for Card Lambda
      uses: actions/cache@v3
      with:
        path: lambdas/card-handler/node_modules
        key: card-${{ runner.os }}-${{ hashFiles('lambdas/card-handler/package-lock.json') }}

    - name: Package Card Lambda Function
      run: |
        npm config set registry https://registry.npmmirror.com
        npm ci
        zip -r ../../card-lambda.zip .
      working-directory: lambdas/card-handler

    # Checkout Lambda
    - name: Cache NPM for Checkout Lambda
      uses: actions/cache@v3
      with:
        path: lambdas/checkout/node_modules
        key: card-${{ runner.os }}-${{ hashFiles('lambdas/card-handler/package-lock.json') }}

    - name: Package Checkout Lambda Function
      run: |
        npm config set registry https://registry.npmmirror.com
        npm ci
        zip -r ../../stripe-checkout-lambda.zip .
      working-directory: lambdas/checkout

    # Sign Token Lambda
    - name: Cache NPM for Sign Token Lambda
      uses: actions/cache@v3
      with:
        path: lambdas/sign-token/node_modules
        key: card-${{ runner.os }}-${{ hashFiles('lambdas/sign-token/package-lock.json') }}

    - name: Package Sign Token Lambda Function
      run: |
        npm config set registry https://registry.npmmirror.com
        npm ci
        zip -r ../../sign-token-lambda.zip .
      working-directory: lambdas/sign-token
